#name: CI

#on: [push]

#jobs:

#  sast_scan:
#    name: Running Bandit Scan
 #   runs-on: ubuntu-latest

#    steps:
  #  - name: Checkout Code
   #   uses: actions/checkout@v4.1.5

  #  - name: Set up Python
   #   uses: actions/setup-python@v2
   #   with:
   #     python-version: 3.11

#    - name: Install Bandit
  #    run: python3 -m pip install bandit
      
 #   - name: bandit running 
  #    run: bandit -r . -f json -o bandit-report.json
      
  #  - name: Upload report bandit
  #    uses: actions/upload-artifact@v4.3.3
   #   if: always()
   #   with:
   #     name: bandit-findings
   #     path: bandit-report.json

name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }} 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}



 # docker_image_scan:
  #  name: Docker image scanning 
  #  runs-on: ubuntu-latest

   # steps:
   # - name: Checkout Code
    #  uses: actions/checkout@v4.1.5  
    
   # - name: Setup Docker
     # uses: docker-practice/actions-setup-docker@v1
    #  uses: crazy-max/ghaction-setup-docker@v3.2.0

    #- name: build 
    #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    
  
    #- name: Build docker image
   #   run: docker build -f Dockerfile -t pygoat:latest .

  #  - name: Docker Scout image running
   #   uses: docker/scout-action@v1.9.3
   #   with: 
    #    dockerhub-user: ${{ secrets.USERNAME }}
    #    dockerhub-password: ${{ secrets.PASSWORD }}
   #     command: quickview, cves
   #     only-serverities: critical, high, medium
    #    sarif-file: scout-report.sarif
    #    exit-code: true
        

  #  - name: Upload report scout
  #    uses: actions/upload-artifact@v4.3.3
  #    if: always()
  #    with:
   #     name: scout-findings
  #      path: scout-report.sarif
