name: CI

on: [push]

jobs:
  docker_image_scan:
    name: Docker image scanning 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4.1.5  
    
    - name: Setup Docker
     # uses: docker-practice/actions-setup-docker@v1
      uses: crazy-max/ghaction-setup-docker@v3.2.0

    - name: build 
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    
  
    #- name: Build docker image
   #   run: docker build -f Dockerfile -t pygoat:latest .

    - name: Docker Scout image running
      uses: docker/scout-action@v1.9.3
      with: 
        dockerhub-user: ${{ secrets.USERNAME }}
        dockerhub-password: ${{ secrets.PASSWORD }}
        command: quickview, cves
        only-serverities: critical, high, medium
        sarif-file: scout-report.sarif
        exit-code: true
        

    - name: Upload report scout
      uses: actions/upload-artifact@v4.3.3
      if: always()
      with:
        name: scout-findings
        path: scout-report.sarif
