name: CI

on: [push]

jobs:
  docker_image_scan:
    name: Docker image scanning 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4.1.5  
    
    - name: Setup Docker
     # uses: docker-practice/actions-setup-docker@v1
     # uses: Byloth/docker-setup-action@v1.1.1
      uses: mr-smithers-excellent/docker-build-push@v6 
     # with: 
      #   docker_version: '25.0'
      with:
        image: repo/image
        tags: v1, latest
        registry: registry-url.io
        dockerfile: Dockerfile
       # username: ${{ secrets.DOCKER_USERNAME }}
      # password: ${{ secrets.DOCKER_PASSWORD }}
  
    #- name: Build docker image
   #   run: docker build -f Dockerfile -t pygoat:latest .

    - name: Docker Scout image running
      uses: docker/scout-action@v1.9.3
      with: 
        dockerhub-user: ${{ secrets.USERNAME }}
        dockerhub-password: ${{ secrets.PASSWORD }}
        command: quickview, cves
        only-serverities: critical, high, medium
        sarif-file: scout-report.sarif
        exit-code: true
        

    - name: Upload report scout
      uses: actions/upload-artifact@v4.3.3
      if: always()
      with:
        name: scout-findings
        path: scout-report.sarif
