name: CI

on: [push]

jobs:
  sast_scan:
    name: Running Bandit Scan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./atg-kali

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4.1.5

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Bandit
      uses: shundor/python-bandit-scan@v1.0
      with: 
        path: "."
        level: high, medium
        confidence: high, medium
        exit_zero: true
      
    - name: Upload report bandit
      uses: actions/upload-artifact@v4.3.3
      if: always()
      with:
        name: bandit-findings
        path: atg-kali/reports/bandit-report.json


